### ISSUE TITLE
CSS suggestions

### ISSUE THREAD

**Issue by philsinatra** [lucia-garzon/idm221-lg852#1]
- [Combine CSS rules with similar properties to reduce redundancy](#combine-css-rules-with-similar-properties-to-reduce-redundancy)
- [Simplify and standardize positioning values in the project blurbs, considering responsiveness](#simplify-and-standardize-positioning-values-in-the-project-blurbs-considering-responsiveness)
- [Minimize the use of !important in CSS to avoid potential conflict](#minimize-the-use-of-important-in-css-to-avoid-potential-conflict)
- [Simplify element sizing and positioning](#simplify-element-sizing-and-positioning)
- [ID based selectors](#id-based-selectors)

## Combine CSS rules with similar properties to reduce redundancy

Here's one example - the `@font-face` declarations. You can consolidate the font faces into one `@font-face` rule per font family instead of having multiple rules:

```css
@font-face {
  font-family: "work_sans";
  src: url('../fonts/worksans-italic-variable.woff2') format('woff2'),
       url('../fonts/worksans-italic-variable.ttf') format('truetype');
  font-weight: 0 900;
  font-style: italic;
}

@font-face {
  font-family: "work_sans";
  src: url('../fonts/worksans-variable.woff2') format('woff2'),  
       url('../fonts/worksans-variable.ttf') format('truetype');
  font-weight: 0 900;
  font-style: normal; 
}
```

Note the `font-family` value is the same. The `font-style` and `src` values integrate both styles into a single font file name.

## Simplify and standardize positioning values in the project blurbs, considering responsiveness

Combine similar styles for project blurbs into a single class to simplify and standardize positioning values. Consider using `nth-child` for specific adjustments to simplify the number of classes.

```css
.blurb {
    z-index: 200;
    position: relative;
    left: 5px;
}

.blurb:nth-child(2) {
    bottom: 37px;
    z-index: 210;
}

.blurb:nth-child(3) {
    bottom: 196px;
}

.blurb:nth-child(4) {
    bottom: 399px;
    z-index: 210;
}
```

## Minimize the use of !important in CSS to avoid potential conflict
  
```diff
.container {
-   width: 100% !important;
+   width: 100%;
}
```  

## Simplify element sizing and positioning

You should be able to code most (if not all) of this design without the need for any use of the `position` property. Try to eliminate as much custom positioning and layering as possible. The horizontal scroll is a result of several, hard coded `left` values. I would try rebuilding the CSS from the top down without using the `position` property, or any `left`, `right`, `top`, or `bottom` properties.

As you work through this, if you encounter a specific issue trying to position something, create an issue on GitHub and tag me (@philsinatra).

## ID based selectors

Update all CSS selectors so they don't use IDs.
